--Query

SELECT COUNT(1) AS msgs_count, 'ITEM_INDUCT_QTAB' AS qtab_name FROM ITEM_INDUCT_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'PO_INDUCT_QTAB' AS qtab_name FROM PO_INDUCT_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'NEW_ITEM_LOC_QTAB' AS qtab_name FROM NEW_ITEM_LOC_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'UPDATE_ITEM_LOC_QTAB' AS qtab_name FROM UPDATE_ITEM_LOC_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'COST_EVENT_QTAB' AS qtab_name FROM COST_EVENT_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'COST_EVENT_THREAD_QTAB' AS qtab_name FROM COST_EVENT_THREAD_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'STKLGR_INSERT_QTAB' AS qtab_name FROM STKLGR_INSERT_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'TAX_EVENT_QTAB' AS qtab_name FROM TAX_EVENT_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'STORE_ADD_QTAB' AS qtab_name FROM STORE_ADD_QTAB UNION
SELECT COUNT(1) AS msgs_count, 'WH_ADD_QTAB' AS qtab_name FROM WH_ADD_QTAB;
